// app/layout.tsx
import type { Metadata } from "next";
// import localFont from "next/font/local";
import "../globals.css";
import Navbar from "@/components/Navbar/page";
import Footer from "@/components/Footer/page";
// const geistSans = localFont({
//     src: "./fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "./fonts/GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });


export const metadata: Metadata = {
    title: "GetUnityCode",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
            <Navbar cartDetails={0} wishlistDetails={0} />
                    {children}
                <Footer />
            </body>
        </html>
    );
}
